export const recommended = [
  {
    title: 'Bỏ Làm Simp Chúa, Ta Có Trong Tay Cả Tỉ Thần Hào',
    chapter: 'Chapter 289',
    time: '9 ngày trước',
    image: 'https://picsum.photos/seed/rec-1/280/180',
  },
  {
    title: 'Toàn Cầu Băng Phong: Ta Chế Tạo Phòng An Toàn',
    chapter: 'Chapter 634',
    time: '2 tháng trước',
    image: 'https://picsum.photos/seed/rec-2/280/180',
  },
  {
    title: 'Vạn Cổ Chí Tôn',
    chapter: 'Chapter 512',
    time: '14 ngày trước',
    image: 'https://picsum.photos/seed/rec-3/280/180',
  },
  {
    title: 'Quỷ Tiến Hóa',
    chapter: 'Chapter 148',
    time: '4 ngày trước',
    image: 'https://picsum.photos/seed/rec-4/280/180',
  },
  {
    title: 'Cảm Kiếm Tuyệt Đối',
    chapter: 'Chapter 176',
    time: '2 ngày trước',
    image: 'https://picsum.photos/seed/rec-5/280/180',
  },
];

export const comics = [
  {
    title: 'Ad Astra - Scipio To Hannibal',
    views: '57',
    comments: '0',
    follows: '599',
    image: 'https://picsum.photos/seed/comic-1/300/420',
    chapters: [
      { name: 'Chapter 27', time: '8 phút trước' },
      { name: 'Chapter 26', time: '9 phút trước' },
      { name: 'Chapter 25', time: '8 phút trước' },
    ],
  },
  {
    title: 'Tiên Võ Đế Tôn',
    views: '337K',
    comments: '5,113,929',
    follows: '3,924,607',
    image: 'https://picsum.photos/seed/comic-2/300/420',
    chapters: [
      { name: 'Chapter 895', time: '40 phút trước' },
      { name: 'Chapter 894', time: '3 ngày trước' },
      { name: 'Chapter 891', time: '3 ngày trước' },
    ],
  },
  {
    title: 'Loạn Đấu Tokyo',
    views: '47K',
    comments: '999',
    follows: '3,135',
    image: 'https://picsum.photos/seed/comic-3/300/420',
    chapters: [
      { name: 'Chapter 103', time: '1 giờ trước' },
      { name: 'Chapter 102', time: '10 giờ trước' },
      { name: 'Chapter 101', time: '1 ngày trước' },
    ],
  },
  {
    title: 'Chàng Rể Mạnh Nhất Lịch Sử',
    views: '766K',
    comments: '1,826',
    follows: '162,959',
    image: 'https://picsum.photos/seed/comic-4/300/420',
    chapters: [
      { name: 'Chapter 391', time: '1 giờ trước' },
      { name: 'Chapter 390', time: '2 giờ trước' },
      { name: 'Chapter 389', time: '5 ngày trước' },
    ],
  },
  {
    title: 'Siêu Cấp Thần Cơ Nhân',
    views: '109K',
    comments: '679,954',
    follows: '207,840',
    image: 'https://picsum.photos/seed/comic-5/300/420',
    chapters: [
      { name: 'Chapter 444', time: '3 giờ trước' },
      { name: 'Chapter 443', time: '3 ngày trước' },
      { name: 'Chapter 442', time: '7 ngày trước' },
    ],
  },
  {
    title: 'Kẻ Tàn Nhẫn Ngày Tận Thế',
    views: '73K',
    comments: '0',
    follows: '2,136',
    image: 'https://picsum.photos/seed/comic-6/300/420',
    chapters: [
      { name: 'Chapter 114', time: '3 giờ trước' },
      { name: 'Chapter 113', time: '4 ngày trước' },
      { name: 'Chapter 112', time: '13 ngày trước' },
    ],
  },
  {
    title: 'Itoko No Ko',
    views: '2K',
    comments: '1,771',
    follows: '4,440',
    image: 'https://picsum.photos/seed/comic-7/300/420',
    chapters: [
      { name: 'Chapter 16.5', time: '1 giờ trước' },
      { name: 'Chapter 16', time: '1 giờ trước' },
      { name: 'Chapter 15', time: '9 ngày trước' },
    ],
  },
  {
    title: 'Hồ Ngôn Bạt Đạo',
    views: '1K',
    comments: '0',
    follows: '33',
    image: 'https://picsum.photos/seed/comic-8/300/420',
    chapters: [
      { name: 'Chapter 42', time: '1 giờ trước' },
      { name: 'Chapter 41', time: '1 giờ trước' },
      { name: 'Chapter 40', time: '1 giờ trước' },
    ],
  },
  {
    title: 'Ứng Dụng Thần Kỳ',
    views: '28K',
    comments: '10',
    follows: '280',
    image: 'https://picsum.photos/seed/comic-9/300/420',
    chapters: [
      { name: 'Chapter 132', time: '1 giờ trước' },
      { name: 'Chapter 131', time: '1 giờ trước' },
      { name: 'Chapter 130', time: '1 giờ trước' },
    ],
  },
  {
    title: 'Gặp Mạnh Thì Càng Mạnh',
    views: '156K',
    comments: '0',
    follows: '6,192',
    image: 'https://picsum.photos/seed/comic-10/300/420',
    chapters: [
      { name: 'Chapter 116', time: '1 giờ trước' },
      { name: 'Chapter 115', time: '4 ngày trước' },
      { name: 'Chapter 114', time: '4 ngày trước' },
    ],
  },
  {
    title: 'Cô Dâu Của Obsidian',
    views: '3K',
    comments: '8,576',
    follows: '2,370',
    image: 'https://picsum.photos/seed/comic-11/300/420',
    chapters: [
      { name: 'Chapter 32', time: '1 giờ trước' },
      { name: 'Chapter 31', time: '2 ngày trước' },
      { name: 'Chapter 30', time: '4 ngày trước' },
    ],
  },
  {
    title: 'Nỗi Ám Ảnh Dành Cho Công Tước Phu Nhân',
    views: '16K',
    comments: '0',
    follows: '204',
    image: 'https://picsum.photos/seed/comic-12/300/420',
    chapters: [
      { name: 'Chapter 28', time: '1 giờ trước' },
      { name: 'Chapter 27', time: '3 ngày trước' },
      { name: 'Chapter 26', time: '7 ngày trước' },
    ],
  },
  {
    title: 'Bệ Hạ, Xin Hãy Quên Tôi Đi',
    views: '10K',
    comments: '0',
    follows: '353',
    image: 'https://picsum.photos/seed/comic-13/300/420',
    chapters: [
      { name: 'Chapter 69', time: '1 giờ trước' },
      { name: 'Chapter 68', time: '14 ngày trước' },
      { name: 'Chapter 67', time: '18 ngày trước' },
    ],
  },
  {
    title: 'Vào Ngày Mà Chị Gái Tôi Qua Đời',
    views: '8K',
    comments: '0',
    follows: '181',
    image: 'https://picsum.photos/seed/comic-14/300/420',
    chapters: [
      { name: 'Chapter 44', time: '2 giờ trước' },
      { name: 'Chapter 43', time: '8 ngày trước' },
      { name: 'Chapter 42', time: '22 ngày trước' },
    ],
  },
  {
    title: 'Lý Trí Của Taika',
    views: '4K',
    comments: '0',
    follows: '87',
    image: 'https://picsum.photos/seed/comic-15/300/420',
    chapters: [
      { name: 'Chapter 60', time: '2 giờ trước' },
      { name: 'Chapter 59', time: '6 ngày trước' },
      { name: 'Chapter 58', time: '14 ngày trước' },
    ],
  },
  {
    title: 'Hợp Đồng Ba Năm Với Tử Thần',
    views: '5K',
    comments: '0',
    follows: '164',
    image: 'https://picsum.photos/seed/comic-16/300/420',
    chapters: [
      { name: 'Chapter 31', time: '2 giờ trước' },
      { name: 'Chapter 30', time: '2 ngày trước' },
      { name: 'Chapter 29', time: '5 ngày trước' },
    ],
  },
];

export const topMonth = [
  { no: '01', title: 'Bách Luyện Thành Thần', chapter: 'Chapter 1295', views: '261K', image: 'https://picsum.photos/seed/top-1/80/110' },
  { no: '02', title: 'Đại Phụng Đả Canh Nhân', chapter: 'Chapter 623', views: '523K', image: 'https://picsum.photos/seed/top-2/80/110' },
  { no: '03', title: 'Tinh Giáp Hồn Tướng', chapter: 'Chapter 357', views: '526K', image: 'https://picsum.photos/seed/top-3/80/110' },
  { no: '04', title: 'Tự Kỷ Luật Ta Đây Bất Khả Chiến Bại', chapter: 'Chapter 132', views: '88K', image: 'https://picsum.photos/seed/top-4/80/110' },
  { no: '05', title: 'Mỗi Tuần Ta Có Một Nghề Nghiệp Mới', chapter: 'Chapter 890', views: '353K', image: 'https://picsum.photos/seed/top-5/80/110' },
  { no: '06', title: 'Chàng Rể Mạnh Nhất Lịch Sử', chapter: 'Chapter 391', views: '766K', image: 'https://picsum.photos/seed/top-6/80/110' },
  { no: '07', title: 'Học Cùng Em Gái, Không Cẩn Thận Trở Thành Vô Địch', chapter: 'Chapter 205', views: '123K', image: 'https://picsum.photos/seed/top-7/80/110' },
];
